### ISSUE TITLE
Mixing variables with different number of levels

### ISSUE THREAD

**Issue by oboril** [Sskki-exe/TaguchiArrayGenerator#1]
Hi, this is a very cool repo, exactly what I was looking for!

Do you think it would be possible to also add option for different variables having different number of levels? E.g. variable A having 3 levels and variables B and C 2 levels each.

Some of the tables are here https://www.york.ac.uk/depts/maths/tables/orthogonal.htm.

Love this repo, simple and functional, keep up the good work!

**Comment by Sskki-exe** [comment]
Thanks for the support.

The orthogonal array genetic algorithm I used only generates arrays where each variable has the same number of levels.

I am unable to formulate an algorithm that generates arrays with varying levels; this may be an impossible problem, which is why people usually look up large databases of tables instead of using a generator.
